Fixed major error
Error: The values were not updating every time I got a assessed a new word/sentence.

Cause: app.get was placed in the wrong section of the code